By: Bishnu Poudel, Mohammed Radwan

## Benchmark Sorting Algorithms: Run timing and store in a data frame then pickle it

In [83]:
import nbimporter
from quick_sort import *

## Create a data frame

In [84]:
import pandas as pd
import numpy as np
columns = ['Sort_Type','Data_Type_or_List_type','List_length','Runtimes','Number_of_repeatitions','Datetime']
df_ = pd.DataFrame( columns=columns)
df_

Empty DataFrame
Columns: [Sort_Type, Data_Type_or_List_type, List_length, Runtimes, Number_of_repeatitions, Datetime]
Index: []

## Timeit function

In [85]:
import numpy as np
import timeit
import copy

def timing_function(number_of_data_points, sort_type, seed_number=12235):
    np.random.seed (seed_number)
    test_data = np.random.random(number_of_data_points ,)
    test_data = list(test_data)

    clock = timeit.Timer ( stmt ='sort_func ( copy ( data) ) ', 
                           globals ={ 'sort_func': sort_type ,
                            'data': test_data ,
                            'copy': copy.copy })
    n_ar , t_ar = clock.autorange ()
    t = clock.repeat ( repeat =7, number = n_ar )
    return t

In [88]:
def get_time_and_write_to_dataframe(Algorithm):
    time_data_points= []

    for i in (10,):
#               ,20,40,80,160,320,640,1280,2560,5120
#               ,10240,20480,40960,81920,163840,327680,655360,1310720
#               ,2621440,5242880,10485760,):
        time =   timing_function(i, Algorithm ) 
        for each_time in time:
#             print (each_time)
            time_data_points.append( {'Sort_Type':Algorithm.__name__ , 'Data_Type_or_List_type':'random'
           ,'List_length':i, 'Runtimes': each_time ,  'Number_of_repeatitions':'7'
           ,'Datetime':pd.Timestamp.now() } )
    return time_data_points

In [89]:
# Do not run this part if you don't want the data again
list_of_dict = get_time_and_write_to_dataframe(sorted)

In [90]:
df_= df_.append(list_of_dict)
df_

,Sort_Type,Data_Type_or_List_type,List_length,Runtimes,Number_of_repeatitions,Datetime
0,sorted,random,10,0.261481,7,2019-10-31 16:27:01.404872
1,sorted,random,10,0.259104,7,2019-10-31 16:27:01.412872
2,sorted,random,10,0.277215,7,2019-10-31 16:27:01.412872
3,sorted,random,10,0.223592,7,2019-10-31 16:27:01.412872
4,sorted,random,10,0.298748,7,2019-10-31 16:27:01.412872
5,sorted,random,10,0.355625,7,2019-10-31 16:27:01.412872
6,sorted,random,10,0.291314,7,2019-10-31 16:27:01.412872

In [95]:
df_.to_csv (r'export_dataframe.csv', index = None, header=True)
df_

,Sort_Type,Data_Type_or_List_type,List_length,Runtimes,Number_of_repeatitions,Datetime
0,sorted,random,10,0.261481,7,2019-10-31 16:27:01.404872
1,sorted,random,10,0.259104,7,2019-10-31 16:27:01.412872
2,sorted,random,10,0.277215,7,2019-10-31 16:27:01.412872
3,sorted,random,10,0.223592,7,2019-10-31 16:27:01.412872
4,sorted,random,10,0.298748,7,2019-10-31 16:27:01.412872
5,sorted,random,10,0.355625,7,2019-10-31 16:27:01.412872
6,sorted,random,10,0.291314,7,2019-10-31 16:27:01.412872

In [93]:
import pickle
name = 'data_frame.txt' 
f=open( name , 'ab')
pickle.dump(df_,f)
f.close()

In [96]:
read= pd.read_pickle("./data_frame.txt")
read

,Sort_Type,Data_Type_or_List_type,List_length,Runtimes,Number_of_repeatitions,Datetime
0,sorted,random,10,0.262095,7,2019-10-31 14:48:00.917440
1,sorted,random,10,0.214780,7,2019-10-31 14:48:00.917440
2,sorted,random,10,0.221988,7,2019-10-31 14:48:00.917440
3,sorted,random,10,0.249518,7,2019-10-31 14:48:00.917440
4,sorted,random,10,0.248136,7,2019-10-31 14:48:00.917440
5,sorted,random,10,0.179612,7,2019-10-31 14:48:00.917440
6,sorted,random,10,0.270123,7,2019-10-31 14:48:00.917440
7,sorted,random,20,0.201368,7,2019-10-31 14:48:02.756097
8,sorted,random,20,0.211886,7,2019-10-31 14:48:02.756097
9,sorted,random,20,0.199484,7,2019-10-31 14:48:02.756097
10,sorted,random,20,0.183100,7,2019-10-31 14:48:02.756097
11,sorted,random,20,0.178878,7,2019-10-31 14:48:02.756097
12,sorted,random,20,0.177645,7,2019-10-31 14:48:02.756097
13,sorted,random,20,0.171961,7,2019-10-31 14:48:02.756097
14,sorted,random,40,0.293931,7,2019-10-31 14:48:04.974155
15,sorted,random,40,0.261734,7,2019-10-31 14:48:04.974155
16,sorted,random,40,0.227608,7,2019-10-31 14:48:04.974155
17,sorted,random,40,0.226382,7,2019-10-31 14:48:04.974155
18,sorted,random,40,0.232287,7,2019-10-31 14:48:04.974155
19,sorted,random,40,0.235192,7,2019-10-31 14:48:04.974155
20,sorted,random,40,0.191137,7,2019-10-31 14:48:04.974155
21,sorted,random,80,0.183609,7,2019-10-31 14:48:06.589389
22,sorted,random,80,0.179760,7,2019-10-31 14:48:06.589389
23,sorted,random,80,0.181543,7,2019-10-31 14:48:06.589389
24,sorted,random,80,0.167848,7,2019-10-31 14:48:06.589389
25,sorted,random,80,0.167033,7,2019-10-31 14:48:06.589389
26,sorted,random,80,0.163663,7,2019-10-31 14:48:06.589389
27,sorted,random,80,0.162527,7,2019-10-31 14:48:06.589389
28,sorted,random,160,0.341619,7,2019-10-31 14:48:11.249242
29,sorted,random,160,0.326398,7,2019-10-31 14:48:11.249242
...,...,...,...,...,...,...
117,sorted,random,655360,1.860194,7,2019-10-31 14:49:00.360114
118,sorted,random,655360,1.926612,7,2019-10-31 14:49:00.360114
119,sorted,random,1310720,4.632213,7,2019-10-31 14:49:30.898816
120,sorted,random,1310720,3.989324,7,2019-10-31 14:49:30.898816
121,sorted,random,1310720,3.547645,7,2019-10-31 14:49:30.898816
122,sorted,random,1310720,2.193859,7,2019-10-31 14:49:30.898816
123,sorted,random,1310720,3.680475,7,2019-10-31 14:49:30.898816
124,sorted,random,1310720,4.372878,7,2019-10-31 14:49:30.898816
125,sorted,random,1310720,4.180261,7,2019-10-31 14:49:30.898816
126,sorted,random,2621440,8.062219,7,2019-10-31 14:50:24.870711
127,sorted,random,2621440,8.452458,7,2019-10-31 14:50:24.870711
128,sorted,random,2621440,7.356156,7,2019-10-31 14:50:24.870711
129,sorted,random,2621440,5.165356,7,2019-10-31 14:50:24.870711
130,sorted,random,2621440,6.115122,7,2019-10-31 14:50:24.870711
131,sorted,random,2621440,5.492347,7,2019-10-31 14:50:24.870711
132,sorted,random,2621440,4.663801,7,2019-10-31 14:50:24.870711
133,sorted,random,5242880,14.430511,7,2019-10-31 14:52:41.528118
134,sorted,random,5242880,14.471754,7,2019-10-31 14:52:41.528118
135,sorted,random,5242880,20.796006,7,2019-10-31 14:52:41.528118
136,sorted,random,5242880,19.686528,7,2019-10-31 14:52:41.528118
137,sorted,random,5242880,17.462381,7,2019-10-31 14:52:41.528118
138,sorted,random,5242880,18.658763,7,2019-10-31 14:52:41.528118
139,sorted,random,5242880,14.776938,7,2019-10-31 14:52:41.528118
140,sorted,random,10485760,34.161587,7,2019-10-31 14:57:37.357037
141,sorted,random,10485760,34.364720,7,2019-10-31 14:57:37.357037
142,sorted,random,10485760,36.641354,7,2019-10-31 14:57:37.357037
143,sorted,random,10485760,40.385404,7,2019-10-31 14:57:37.357037
144,sorted,random,10485760,43.257374,7,2019-10-31 14:57:37.357037
145,sorted,random,10485760,29.558077,7,2019-10-31 14:57:37.357037
146,sorted,random,10485760,35.635236,7,2019-10-31 14:57:37.357037

In [97]:
pwd

'C:\\Users\\admin\\Desktop\\INF221\\termpaper01\\Sent_to_Mohammed'